services:
  app:
    container_name: app
    build: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
   
    
