import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "./providers";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className + (" flex flex-col min-h-screen")}>
        <Providers>
          <div id="modal-portal" />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
