export const recommendationsData = [
    {
        article: "Mir-10554",
        brand: "…",
        color: "…",
        discounted_price: "10 000",
        id: 100,
        main_image: "/cardProduct.png",
        name: "Боди Alaia",
        fullPrice: "15 000",
    },
    {
        article: "Mir-10554",
        brand: "…",
        color: "…",
        discounted_price: "10 000",
        id: 101,
        main_image: "/cardProduct.png",
        name: "Боди Alaia",
        fullPrice: "15 000",
    },
    {
        article: "Mir-10554",
        brand: "…",
        color: "…",
        discounted_price: "10 000",
        id: 102,
        main_image: "/cardProduct.png",
        name: "Боди Alaia",
        fullPrice: "15 000",
    },
    {
        article: "Mir-10554",
        brand: "…",
        color: "…",
        discounted_price: "10 000",
        id: 103,
        main_image: "/cardProduct.png",
        name: "Боди Alaia",
        fullPrice: "15 000",
    },
]